config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tickets
  # ユーザ登録
  get 'users/new'
  post 'users/create'

  # ログイン/ログアウト
  root 'sessions#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # チケット
  get 'top', to: 'tickets#show'
  get 'detail', to: 'tickets#detail'
  get 'create', to: 'tickets#new'
  post 'create', to: 'tickets#create'
  get 'edit', to: 'tickets#edit'
  get 'upgrade', to: 'tickets#upgrade'
  get 'downgrade', to: 'tickets#downgrade'
  patch 'update', to: 'tickets#update'
  delete 'destroy', to: 'tickets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user

  enum status:{ TODO: 0, DOING: 1, DONE: 2}
  validates :title,
    presence: true,
    length: { maximum: 30 }
  validates :content,
    presence: true,
    length: { maximum: 1000 }
  validates :status,
    inclusion: { in: ['TODO','DOING', 'DONE'] }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ticket

  validates :name, presence: true,length: { maximum: 10 }
  validates :user_id, presence: true, uniqueness: true,length: { maximum: 10 }
  has_secure_password validations: true

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :current_user
  before_action :require_sign_in!
  helper_method :signed_in?

  protect_from_forgery with: :exception

  def current_user
    remember_token = User.encrypt(cookies[:user_remember_token])
    @current_user  ||= User.find_by(remember_token: remember_token)
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:user_remember_token] = remember_token
    user.update!(remember_token: User.encrypt(remember_token))
    @current_user = user
  end

  def sign_out
    cookies.delete(:user_remember_token)
  end
  
  def signed_in?
    @current_user.present?
  end

  private
  def require_sign_in!
    redirect_to controller: 'sessions', action: 'new' unless signed_in?
  end
end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController
  skip_before_action :require_sign_in!, only: [:new, :create]
  before_action :set_user, only: [:create]
  
  # ログインページを表示するだけなので何もしない
  def new
    if signed_in?
      redirect_to controller: 'tickets', action: 'show'
    end
  end

  # セッションを取得(ログイン)
  def create
    if @user.authenticate(session_params[:password])
      sign_in(@user)
      # トップページに繊維
      redirect_to controller: 'tickets', action: 'show'
    else
      flash.now[:error_messages] = ['Incorrect userid or password']
      render 'new'
    end
  end

  # セッションを破棄(ログアウト)
  def destroy
    sign_out
    redirect_to action: 'new'
  end
  
  private
    def set_user
      @user = User.find_by!(user_id: session_params[:user_id])
    rescue
      flash.now[:error_messages] = ['Incorrect userid or password']
      render 'new'
    end

    def session_params
      params.require(:session).permit(:user_id, :password)
    end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:detail, :edit, :update, :destroy, :upgrade, :downgrade]
  before_action :set_user
  before_action :require_sign_in!
  before_action :unauthorized_access, only: [:detail, :edit, :update, :destroy, :upgrade, :downgrade]

  # チケットの一覧を表示する
  def show
    @todo_tickets = Ticket.where(user_id: @user.id).where(status: :TODO)
    @doing_tickets = Ticket.where(user_id: @user.id).where(status: :DOING)
    @done_tickets = Ticket.where(user_id: @user.id).where(status: :DONE)
  end

  # チケットの詳細を表示する
  def detail
    if !collect_user?
      redirect_to action: 'show'  
    end
  end

  # チケット作成画面を表示
  def new
    @ticket = Ticket.new(flash[:ticket])
  end

  # チケットを作成する
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = @user.id

    if @ticket.save
      # トップページに繊維
      redirect_to action: 'show'
    else
      # チケット作成ページに繊維
      flash[:error_messages] = @ticket.errors.full_messages
      flash[:ticket] = @ticket
      redirect_back(fallback_location: root_path)
    end
  end

  # チケットを編集する
  def edit
    # フラッシュで編集時のオブジェクトが流れてきた時のみ@ticketにセットする
    if flash[:ticket]
      @ticket = Ticket.new(flash[:ticket])
    end
    @status = { TODO: 'TODO', DOING: 'DOING', DONE: 'DONE'}
  end

  # チケットを更新
  def update
    if @ticket.update(ticket_params)
      redirect_to action: 'show'
    else
      ticket = Ticket.new(ticket_params)
      flash[:error_messages] = @ticket.errors.full_messages
      flash[:ticket] = ticket
      redirect_back(fallback_location: root_path)
    end
  end

  # チケットをアップグレード
  def upgrade
    if @ticket.status == 'TODO'
      @ticket.update(status: :DOING)
    elsif @ticket.status == 'DOING'
      @ticket.update(status: :DONE)
    end
    redirect_to action: 'show'
  end

  # チケットをダウングレード
  def downgrade
    if @ticket.status == 'DOING'
      @ticket.update(status: :TODO)
    elsif @ticket.status == 'DONE'
      @ticket.update(status: :DOING)
    end
    redirect_to action: 'show'
  end
  
  # チケットを削除
  def destroy
    @ticket.destroy
    redirect_to action: 'show'
  end

    private
      # 選択したチケットをセット
      def set_ticket
        @ticket = Ticket.find(params[:id])
      rescue
        flash[:error_messages] = ['Error! Unauthorized access.']
        redirect_to action: 'show'
      end

      # ログイン中のuserをセット
      def set_user
        @user = current_user
      end

      # 編集されたくないものは取り除く
      def ticket_params
        params.require(:ticket).permit(:title, :content, :status)
      end

      # チケットの作成者が現在のユーザか？
      def collect_user?
        @user.ticket.exists?(params[:id])
      end

      # 不正なチケットアクセスの対処
      def unauthorized_access 
        if !collect_user?
          flash[:error_messages] = ['Error! Unauthorized access.']
          redirect_to action: 'show'
        end
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_sign_in!, only: [:new, :create]
  
  def new
    @user = User.new(flash[:user])
  end

  def create
    user = User.new(user_params)
    if user.save
      # トップページに繊維
      user.authenticate(user.password)
      sign_in(user)
      redirect_to controller: 'tickets', action: 'show'
    else
      # 書き込み失敗
      flash[:error_messages] = user.errors.full_messages
      flash[:user] = user
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :user_id, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleKanbanApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <p class="logo"> <%= link_to 'SimpleKanbanApp', top_path() %><p>
    <% if signed_in? %>
      <p class="new-ticket"><%= link_to 'create ticket', {controller: :tickets, action: :new} %></p>
      <p class="logout"><%= link_to 'logout', {controller: :sessions, action: :destroy}, {method: :delete, data: {confirm: 'ログアウトしますか？'}} %></p> 
    <% end %>
  </header>
  <div class="header-heightfix"></div>
    <%= yield %>
  
  <footer>
  
  </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class="error-messages">
    <% flash[:error_messages].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </div>
<% end %>

app/views/tickets/detail.html.erb
<div class="detail-container">
  <h2 class="detail-title" > 
    <%= @ticket.title %>
    <hr> 
  </h2>
  <div class="detail-content">
    <%= @ticket.content %>
    <hr>
  </div>
  <div class="detail-info">
    status : <%= @ticket.status%> <br> 
    create date : <%= @ticket.created_at.strftime('%Y/%m/%d %H:%M') %>
    <hr>
  </div>
  <div class="detail-submit">
    <%= link_to 'back', {action: :show}, class: :btn %>
    <%= link_to 'edit', edit_path(id: @ticket.id), class: :btn %>
    <%= link_to 'delete', destroy_path(id: @ticket.id), method: :delete, data: { confirm: '削除しますか?' }, class: :btn %>
  </div>
</div>

app/views/tickets/edit.html.erb
<div class="form">
  <%= render 'shared/error_messages' %>
  <ul>
    <%= form_for @ticket do |f| %>
      <li>
        <%= f.label :title %>
        <%= f.text_field :title %><br />
      </li>
      <li>
        <%= f.label :content %>
        <%= f.text_area :content, cols: 40, rows: 10 %><br />
      </li>
      <li>
        <%= f.select :status, @status %>
      </li>
      <li>
        <%= f.submit 'edit', class: :btn %>
      </li>
    <% end %>
    <li>
      <%= link_to 'back', {action: :show}, class: :btn %>
    </li>
  </ul>
</div>

app/views/tickets/new.html.erb
<div class="form">
  <%= render 'shared/error_messages' %>
  <ul>
    <%= form_for @ticket, :url => {:action => :create}  do |f| %>
      <li>
        <%= f.label :title %>
        <%= f.text_field :title %><br />
      </li>
      <li>
        <%= f.label :content %>
        <%= f.text_area :content, cols: 40, rows: 10 %><br />
      </li>
      <li>
        <%= f.submit 'create', class: :btn %>
      </li>
    <% end %>
    <li>
      <%= link_to 'back', {action: :show}, class: :btn %>
    </li>
  </ul>
</div>

app/views/tickets/show.html.erb
<div class="ticket-container clearfix">
<%= render 'shared/error_messages' %>
  <h1>TODO</h1>
  <hr>
  <% @todo_tickets.each do |ticket| %>
    <div class="ticket">
      <div class="ticket-title">
        <p><%= link_to ticket.title, detail_path(id: ticket.id) %></p>
      </div>
      <p class="ticket-contents"><%= truncate(ticket.content, length: 100) %></p>
      <div class="ticket-edit">
        <%= link_to 'Edit', edit_path(id: ticket.id), class: "btn" %>
        <%= link_to 'Delete', destroy_path(id: ticket.id), method: :delete, data: { confirm: '削除しますか?' }, class: "btn " %>
      </div>
      <div class="ticket-status-change">
        <p class="btn none">downgrade status</p>
        <%= link_to 'upgrade status', upgrade_path(id: ticket.id), class: "btn" %>
      </div>
    </div>
  <% end %>
</div>

<div class="ticket-container clearfix">
  <h1>DOING</h1>
  <hr>
  <% @doing_tickets.each do |ticket| %>
    <div class="ticket">
      <div class="ticket-title">
        <p><%= link_to ticket.title, detail_path(id: ticket.id) %></p>
      </div>
      <p class="ticket-contents"><%= truncate(ticket.content, length: 100) %></p>
      <div class="ticket-edit">
        <%= link_to 'Edit', edit_path(id: ticket.id), class: "btn" %>
        <%= link_to 'Delete', destroy_path(id: ticket.id), method: :delete, data: { confirm: '削除しますか?' }, class: "btn " %>
      </div>
      <div class="ticket-status-change">
        <%= link_to 'downgrade status', downgrade_path(id: ticket.id), class: "btn" %>
        <%= link_to 'upgrade status', upgrade_path(id: ticket.id), class: "btn" %>
      </div>
    </div>
  <% end %>
</div>

<div class="ticket-container clearfix">
  <h1>DONE</h1>
  <hr>
  <% @done_tickets.each do |ticket| %>
    <div class="ticket">
      <div class="ticket-title">
        <p><%= link_to ticket.title, detail_path(id: ticket.id) %></p>
      </div>
      <p class="ticket-contents"><%= truncate(ticket.content, length: 100) %></p>
      <div class="ticket-edit">
        <%= link_to 'Edit', edit_path(id: ticket.id), class: "btn" %>
        <%= link_to 'Delete', destroy_path(id: ticket.id), method: :delete, data: { confirm: '削除しますか?' }, class: "btn " %>
      </div>
      <div class="ticket-status-change">
        <%= link_to 'downgrade status', downgrade_path(id: ticket.id), class: "btn" %>
        <p class="btn none">upgrade status</p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :url => {:action => :create} do |f| %>
  <% if @user.errors.any? %>
    エラー：<%= @user.errors.count %>
    <ul>
      <%= @user.errors.fullmessages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %><br />

  <%= f.label :user_id %><br />
  <%= f.text_field :user_id %>

  <%= f.label :password %><br />
  <%= f.text_field :password %>

  <%= f.label :password_confirmation %><br />
  <%= f.text_field :password_confirmation %>

  <%= f.submit '登録' %>
<% end %>

app/views/users/new.html.erb
<div class="form">
  <%= render 'shared/error_messages' %>
  <ul>
    <%= form_for @user, :url => {:action => :create} do |f| %>
      <li>
        <%= f.label :name, "name" %>
        <%= f.text_field :name %>
      </li>
      <li>
        <%= f.label :user_id, "user id" %>
        <%= f.text_field :user_id %>
      </li>
      <li>
        <%= f.label :password, "password" %>
        <%= f.password_field :password %>
      </li>
      <li>
        <%= f.label :password_confirmation, "password confirm" %>
        <%= f.password_field :password_confirmation %>
      </li>
      <li>
        <%= f.submit 'create' ,class: :btn %>
      </li>
    <% end %>
  </ul>
</div>

app/views/zzz/top.html.erb
<h1>toppage</h1>
<% if ! signed_in? %>
  サインイン
<% end %>
<%= @user.name %>

<%= link_to 'logout', {controller: :sessions, action: :destroy}, {method: :delete, data: {confirm: 'ログアウトしますか？'}} %>